apiVersion: v1
kind: PersistentVolume
metadata:
  name: known-faces-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/known-faces"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/db"
